### ISSUE TITLE
[Request] Support Auto Roll NPC Save D&D5e

### ISSUE THREAD

**Issue by PaulWRoberts** [ElfFriend-DnD/foundryvtt-retroactive-advantage-5e#4]
Show the buttons and allow for retroactive advantage for NPC saving throws generated by Auto Roll NPC Save D&D5e.

**Comment by akrigline** [comment]
It's pretty unlikely that this will happen simply because these two modules don't want to know that each other exists. If someone were to be motivated enough to try it, I'm interested to hear what solution they come up with. But I'm thinking this is a pretty solid "won't do" from me.
