### ISSUE TITLE
Warning and an Error when changing Disadvantage/Normal/Advantage

### ISSUE THREAD

**Issue by InnilToo** [ElfFriend-DnD/foundryvtt-retroactive-advantage-5e#7]
Browser: Edge
FVTT: v10
DnD5e: 2.0.2

When I change between any of the 3 options I get this on the console.
![image](https://user-images.githubusercontent.com/33260912/188399560-5209d314-e2e4-40d2-8c30-089b1174ba76.png)
Everything is seemingly working tho.

**Comment by akrigline** [comment]
Interesting. Looks like something isn't interacting with dice so nice properly.

Thanks, I'll look into it

**Comment by InnilToo** [comment]
The bug is no longer present.
